### ISSUE TITLE
Left Chat Moves in Windowed Mode

### ISSUE THREAD

**Issue by Rotoboy** [Eclipse-/EclipseUI#30] opened 2011-02-19 01:55 UTC
No error but if you switch to windowed mode the left chat tabs move requiring a /rl to correct.

Here's a SS.

http://img33.imageshack.us/i/euiwindowmode.jpg/

**Comment by Eclipse-** [comment] 2011-02-19 12:37
Was this with a clean WTF installation?

**Comment by Rotoboy** [comment] 2011-02-19 19:26
It was, yes.  Just reinstalled and had the same issue.

**Comment by Eclipse-** [comment] 2011-02-20 12:28
I'm going to close this ticket because there is another ticket open with the same issue. The issue is being looked into.

**Closed as completed by Eclipse-** 2011-02-20 12:28 UTC
